### ISSUE TITLE
asyncio.async is deprecated since python 3.4.4, use asyncio.ensure_future instead

### ISSUE THREAD

**Issue by nils-van-zuijlen** [harvimt/quamash#106]
As python 3.3 is not actively supported by the PSF, could you replace all deprecated `asyncio.async` in the code by the equivalent `asyncio.ensure_future` ?

https://docs.python.org/3.5/library/asyncio-task.html#asyncio.ensure_future

`asyncio.async` has been removed in python 3.7. You will have to replace it anyway at some time.

**Comment by nils-van-zuijlen** [comment]
Oh, and if you don't want to do it, could you direct me to another way, with support for python 3.7, of getting an asyncio-like loop from PyQt5 ?

**Comment by nils-van-zuijlen** [comment]
Oh, and if you have a way that only works with PySide2, I'll take it too.

**Comment by henry232323** [comment]
I do believe that the `asyncio.async` issue was patched. I changed all the instances in #94 back in July of last year. I'm able to run it on 3.7 without any issues, have you tried updating?

**Comment by nils-van-zuijlen** [comment]
Oops, I did not try it.
