### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by aknuds1** [harvimt/quamash#12]
I noticed there are currently various test failures on Windows after pulling your latest changes into my fork, @harvimt.

**Comment by harvimt** [comment]
Tests that are failing (PySide on win2012R2x64)

* test_can_read_subprocess and test_can_communicate_subprocess - problem with test and carriage returns vs new lines easy fix, patch coming
* test_regression_bug13 - Event loop stopped before Future completed

Fixing the test_can_read/communicate_subprocess test fixed the test_regression_bug13 test, this seems to indicate that something is fragile w/ regards to teardown (or something) (the exceptions caused some teardown code to not run, thus affecting the other test further down the line)
