### ISSUE TITLE
Release 0.6.2

### ISSUE THREAD

**Issue by dderjoel** [harvimt/quamash#131]
#130 says, this package should be updated in PyPI
On the [AUR](https://aur.archlinux.org/packages/python-quamash), there is to comments regarding the python 3.10 incompatibility which is fixed by 1e9047bec739dbc9d6ab337fc1a111a8b1090244

What would stop us from bumping this package to the next release?
Then we could ping the repo maintainers to point to this.

**Comment by harvimt** [comment]
who's "we" it's just me.

You need to fix all the code rot. which generally means setting up a lot of
CI/testing configuration.

**Comment by dderjoel** [comment]
Thought with 'we'/'us' as the community.

I mean from the last release and the current state, the only changes that I see is a change in the Readme, and the said fix for python 3.10. 

So my idea was to tag this current commit with 0.6.2, and publish this then on the PyPI (I am unfamiliar with how the CD for this typically goes).
After that, the AUR package can be updated, as it gets the package from the PyPI.

**Comment by harvimt** [comment]
I have the password to the PyPI account. I don't understand how you think
this works.

**Comment by dderjoel** [comment]
Okay maybe I ask differently:

Can you publish the current master as the next version on PyPI?

**Comment by harvimt** [comment]
Not in its present form.
