### ISSUE TITLE
Support / Development real-time communication platform

### ISSUE THREAD

**Issue by horazont** [harvimt/quamash#21]
I propose that this project obtains a real-time communication platform.

If this proposal gets accepted, I suggest that we use IRC or XMPP. With respect to IRC, the [freenode](http://freenode.net/) and [OFTC](http://www.oftc.net/) networks seem to be commonly used for open source projects. Currently, #quamash on freenode is unused.

Use cases would for instance be:

* Support for users, also from user-to-user, not only dev-to-user
* Discuss the validity of small issues before placing an issue on github.

What are your thoughts? @harvimt @aknuds1

**Comment by aknuds1** [comment]
I am on IRC, but it isn't as if I hang out there much. I mostly use it to
find help with specific projects. I wouldn't mind if there were a #quamash
channel. I think I'd prefer Freenode though since almost all my channels
are on this network.

**Comment by horazont** [comment]
In case there exists some interest on that, I started hanging out in #quamash on the Freenode network.

**Comment by harvimt** [comment]
I've setup Gitter on @aknuds1's recommendation, though I've seen other projects use it.

It's here: https://gitter.im/harvimt/quamash?utm_source=share-link&utm_medium=link&utm_campaign=share-link
