### ISSUE TITLE
asyncio.async working?

### ISSUE THREAD

**Issue by DietmarSchwertberger** [harvimt/quamash#22]
Hi!

Please have a look at the minimum example below.
I'ts working. The coroutine will print out 0, 1, 3,...
But when I change the True to False, nothing will happen.
Shouldn't asyncio.async(...) work as well as loop.run_unti_complete(...)?

I'm using Python 3.4.1 with PyQt5 under Windows 7.

Regards,

Dietmar

```python
import sys
import asyncio


from PyQt5.QtWidgets import QApplication
from quamash import QEventLoop

app = QApplication(sys.argv)
loop = QEventLoop(app)

@asyncio.coroutine
def coroutine():
    n = 0
    while True:
        print(n)
        yield from asyncio.sleep(1.0)
        n += 1

if True:
    with loop:
        loop.run_until_complete(coroutine())
else:
    asyncio.async( coroutine() )
    with loop:
        loop.run_forever()
```

**Comment by harvimt** [comment]
What about

loop.run_until_complete(asyncio.async(coroutine())?

(not that you should have to do that)

Windows isn't as well tested as *nix platforms at the moment.

I'll see if I can replicate this.

**Comment by harvimt** [comment]
I tested on the depinject branch on Windows Server 2012

these three new tests:

```python
def test_can_call_coroutine(loop):
	was_called = False
	@asyncio.coroutine
	def test_coro():
		nonlocal was_called
		yield from asyncio.sleep(.1)
		was_called = True
		return True

	assert loop.run_until_complete(test_coro())
	assert was_called

	
def test_can_call_coroutine_with_async(loop):
	was_called = False
	@asyncio.coroutine
	def test_coro():
		nonlocal was_called
		yield from asyncio.sleep(.1)
		was_called = True
		return True

	assert loop.run_until_complete(asyncio.async(test_coro()))
	assert was_called

	
def test_can_call_coroutine_with_async(loop):
	was_called = False
	@asyncio.coroutine
	def test_coro():
		nonlocal was_called
		was_called = True
		yield from asyncio.sleep(.1)
		loop.stop()
		return True

	asyncio.async(test_coro())
	loop.run_forever()
	assert was_called
```

**Comment by harvimt** [comment]
I know the problem it's sitting right in front of use, you aren't setting the event loop.

Either use `asyncio.set_event_loop(loop)` or `with loop: ...` (as in the example on the front page) or `asyncio.async(test_coro(), loop=loop)`

Otherwise asyncio will put the coroutine on the wrong even loop.

**Comment by harvimt** [comment]
nm, you're totally doing `with loop: ...`, but it's still the right problem, you're doing `asyncio.async(...)` *before* setting the loop (with loop just sets the event loop with asyncio.set_event_loop and then sets it back when it's done). As noted, the other option is to set the event loop manually on asyncio.async with the loop keyword argument.

**Comment by aknuds1** [comment]
Yep, it works so long as you install the loop as @harvimt is saying.

**Comment by harvimt** [comment]
how does everyone feel about deprecating the context manager? It's non-standard/isn't in the PEP

Then updated the readme to make a note to call `asyncio.set_event_loop()` immediately after instantiating the event loop?

Current Example (reduced for size)

```python

app = QApplication(sys.argv)
progress = QProgressBar()
loop = QEventLoop(app)

progress.setRange(0, 99)
progress.show()

# ... snip ...

with loop:
    loop.run_until_complete(master())
```
```python
app = QApplication(sys.argv)
loop = QEventLoop(app)
asyncio.set_event_loop(loop)

progress = QProgressBar()

progress.setRange(0, 99)
progress.show()

# ... snip ...

loop.run_until_complete(master())
```

**Comment by aknuds1** [comment]
It's better to stick with the standard, so I agree, get rid of the context manager installation side effect (providing that this is non-standard behaviour, I haven't double checked).

However, isn't it still a good idea to use the context manager to close the loop after it's done with?

**Comment by harvimt** [comment]
I created a new issue, so @DietmarSchwertberger doesn't get spammed with too much off-topic ness.

**Comment by DietmarSchwertberger** [comment]
Am 15.01.2015 um 02:05 schrieb Mark Harviston:
>
> how does everyone feel about deprecating the context manager? It's 
> non-standard/isn't in the PEP
>
> Then updated the readme to make a note to call 
> |asyncio.set_event_loop()| immediately after instantiating the event loop?
>
> Current Example (reduced for size)
>
I totally agree. This is much more transparent than the context manager.

My program is working now as expected.

Thanks a lot,

Dietmar
