### ISSUE TITLE
Exceptions in callbacks cause tests to terminate and potentially succeed

### ISSUE THREAD

**Issue by horazont** [harvimt/quamash#24]
Fellow quamashians,

I came across this while debugging another issue I am having, and this makes writing tests quite hard if you don’t know about this.

Exceptions in callbacks are swallowed by the pytest setup. In a setup like the following:

	def test_scheduling(loop, sock_pair):
		s1, s2 = sock_pair
		fd = s1.fileno()
		cb_called = asyncio.Future()
		def writer_cb(fut):
			fut.set_result(None)
		def fut_cb(fut):
			loop.remove_writer(fd)
			cb_called.set_result(None)
	
		fut = asyncio.Future()
		fut.add_done_callback(fut_cb)
		loop.add_writer(fd, writer_cb, fut)
		loop.run_until_complete(cb_called)

What happens here is the following (part of this is part of another bug):

1. writer_cb gets called, sets the future to None
2. writer_cb gets called again (before fut_cb, which is part of another bug), but trying to set the future to None will result in an exception
3. event loop gets stopped by the exception (due to the code in test_qeventloop.py, loop(request, application))
4. run_until_complete returns successfully as the future is already done

My proposal is that either exceptions in callbacks in tests should be treated critically and cause the test to fail, or they should be treated like in live quamash. I don’t know which of the two options I prefer though.

cheers,
horazont

**Comment by harvimt** [comment]
yeah, I've noticed that too. Exceptions in tests should probably always result in the testing failing.

**Comment by harvimt** [comment]
The solution btw, is to call loop.set_exception_handler and then use some pytest utility function to manually fail the test (`pytest.fail` probably)

**Comment by harvimt** [comment]
ok, so pytest.fail raises an exception... and as you might imagine raising an exception in an exception handler goes over really well.

So instead I have to set an exception handler and put the exceptions somewhere. then when the test completes check that bucket (I'm using a list) for contents and then fail.

Note that the traceback given is terrible, but if you pass `--pdb` to `py.test` you can inspect the `additional_exceptions` variable (it's a `list` of `dict`s) which has more info in it (including better tracebacks)
