### ISSUE TITLE
Tests and my own application fail with Python3.4.2 (Debian). Many InvalidStateError

### ISSUE THREAD

**Issue by sfrazt** [harvimt/quamash#27]
Hi,

downloaded and installed quamash hours ago with
pip3 install quamash

Get massive amounts of
asyncio.futures.InvalidStateError: FINISHED: <Future finished result=None>

test:
python3 /usr/lib/python3/dist-packages/pytest.py test_qeventloop.py >test.log
test.log:
http://pastebin.com/bh7ZabZq

Here a minimal example
http://pastebin.com/guEcTN1Q
and output
http://pastebin.com/PWCNn3Hc

**Comment by aknuds1** [comment]
I'm trying to re-create, but in my Ubuntu 14.10 VM I can only get to the third doctest before Python crashes and dumps core.

**Comment by sfrazt** [comment]
If this is a help: I'm using Debian Sid as said with Python 3.4.2 and quamash 0.4.1.

**Comment by harvimt** [comment]
> loop.run_until_complete(self.exec())

what?
don't do this, `run_until_complete` can only take coroutines or futures anyway, not regular callables; besides, you wouldn't want to do this, because, `loop.run_until_complete` will call `loop.run_forever` and `loop.run_forever` calls `app.exec`. just use `loop.run_forever()`

On my machine, I get this error:
```
Traceback (most recent call last):
  File "mintest.py", line 48, in <module>
    App()
  File "mintest.py", line 43, in __init__
    loop.run_until_complete(self.exec())
  File "/mnt/fuzzy/Development/quamash/quamash/__init__.py", line 281, in run_until_complete
    future = asyncio.async(future, loop=self)
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 510, in async
    raise TypeError('A Future or coroutine is required')
TypeError: A Future or coroutine is required
```

And no errors if I swap out `loop.run_until_complete()` with `loop.run_forever()`

I'll fire up a Debian Sid instance inside of docker and see if I can make it get the same error you're getting.

couple of other notes, this code:

```
            if additional_exceptions:
                   raise additional_exceptions[0]['exception']
```

isn't in 0.4.1, so you must be using master.

**Comment by sfrazt** [comment]
> what?
Thanks for the information. I'm still new to async(io) and OOP concepts.

> And no errors if I swap out loop.run_until_complete(self.exec()) with loop.run_forever()

I can't confirm. Still same behaviour.

Additionally: The errors appear until the text "TCP init
connection_made" appears. If i don't create a MainWindow (means in exmaple no Window or Widget at all) by uncommenting the 3 MainWindow lines the error messages don't stop flooding. Very strange.

> isn't in 0.4.1, so you must be using master.
Ok.
"__version__ = '0.4.1'" is then in master version of quamash/__init__.py

**Comment by harvimt** [comment]
>  "__version__ = '0.4.1'" is then in master version of quamash/__init__.py

I could see how that would be confusing, but the "official" numbered releases are tagged in git (version-0.4.1, version-0.4, etc.) or on pypi.

The tests aren't shipped with the sdists on pypi (maybe they should be?), so to run the tests you do need the version on git.

I've been able to reproduce @aknuds1 errors (segfaults) with a docker instance I think.

Steps to reproduce (once docker is installed/setup on your system)

```
$ docker pull extellisys/debian-sid
$ docker run -ti extellisys/debian-sid /bin/sh
# apt-get update
# apt-get install -y python3 python3-pip python3-pyqt4 python3-pytest git
# git clone http://github.com/harvimt/quamash
# cd quamash
# git checkout version-0.4.1
# python3 setup.py develop
# py.test-3.4
```

And then it just segfaults before even running the first test. (same on HEAD commit)

**Comment by aknuds1** [comment]
Any idea how to debug the crash @harvimt?

**Comment by harvimt** [comment]
Ah. well I think I know why it's crashing on the docker instance: no X server.

As for @sfrazt's errors? no idea still.

**Comment by harvimt** [comment]
Yeah. no idea what is wrong.
If I do this:

```
$ docker pull extellisys/debian-sid
$ docker run -ti extellisys/debian-sid /bin/sh
# apt-get update
# apt-get install -y python3 python3-pyqt4 python3-pytest git xvfb
# git clone http://github.com/harvimt/quamash
# cd quamash
# git checkout version-0.4.1
# export DISPLAY=:0
# Xvfb&
# python3 setup.py develop
# for i in `seq 0 10`; do py.test-3.4 2>&1 >/dev/null && echo success; done | grep success | wc -l
```
I get segfaults about 50% of the time, but not all the time. (regardless of tag/master)

@sfrazt Is there a way you can test on another platform (Ubuntu? CentOS, something)

It seems weird that it would work fine on Ubuntu, but not Debian, and if so it's definitely a problem.

A docker container inside a virtualbox vm on a windows machine might not even be close enough to @sfrazt's system to truly replicate the bug.

**Comment by aknuds1** [comment]
@harvimt Seems to me, from testing, that it's the re-instantiation of QApplication that's causing the segfault. The second time QApplication gets instantiated by a doctest, there's a crash.

**Comment by sfrazt** [comment]
> Steps to reproduce (once docker is installed/setup on your system)
>
> > $ docker pull extellisys/debian-sid
> > $ docker run -ti extellisys/debian-sid /bin/sh
> > # apt-get update
> > # apt-get install -y python3 python3-pip python3-pyqt4 python3-pytest git

You missed the "python3-setuptools" in the apt-get install line and i recommend a full "apt-get dist-upgrade -y" just after apt-get update


I tried this
> python3 /usr/lib/python3/dist-packages/pytest.py test_qeventloop.py

with test_qeventloop from master and 0.4.1 (while not changing the version installed via pip)
0.41 version of the file.: No errors and 1 warning
master version: The errors i started the report with

Playing now with docker.. Will write a new comment when i have results

**Comment by aknuds1** [comment]
I've fixed the doctest crashes for me at least, in a [PR](https://github.com/harvimt/quamash/pull/28).

**Comment by sfrazt** [comment]
Problem resolved with quamash from master
> pip3 install --upgrade git+http://github.com/harvimt/quamash@master

Some more tests:
> python3 /usr/lib/python3/dist-packages/pytest.py test_qeventloop.py

1. test_qeventloop.py from git@master
1.1 quamash via pip3 pip3 install git+http://github.com/harvimt/quamash@version-0.4.1
Result errors (always the same i reported in first post)
1.2 quamash via pip3 pip3 install git+http://github.com/harvimt/quamash@master
All fine! Tests and my application

2. test_qeventloop.py from git@version-0.4.1
All fine for the tests with both qumash@master and quamash@0.4.1
Still the test application produces many errors with qumarsh@0.4.1

**Comment by harvimt** [comment]
Interesting.

@sfazt master just changed (slightly) all changes to tests, so you may want to test again.

@aknuds1 If master really does have bug fixes in it that we didn't know about, we should probably release this and call it 0.5 because of the potentially breaking changes to how the context manager works. I was gonna wait for more features, but release early and often tis the open source way.

@sfrazt is there any reason to do `python3 /usr/lib/python3/dist-packages/pytest.py` vs just `py.test-3.4`? I wouldn't think so. Did you install py.test with pip or apt-get? (it shouldn't matter, but calling py.test-3.4 seems more canonical to me)

Here's what I'm doing to more closely match @sfrazt's setup.

```
$ docker pull extellisys/debian-sid
$ docker run -ti extellisys/debian-sid /bin/sh
# apt-get update
# apt-get dist-upgrade -y
# apt-get install -y python3 python3-pip python3-python3-pyqt4 python3-pytest git xvfb curl
# export DISPLAY=:0
# Xvfb&
git clone http://github.com/harvimt/quamash
# cd quamash
# py.test-3.4  # run all tests -- no segfaults!
# cd tests
# pip3 install git+http://github.com/harvimt/quamash@master
# py.test-3.4 test_qeventloop.py  # no segfaults either!
# cd /
# curl -o mintest.py https://gist.githubusercontent.com/harvimt/2d4b4228b89ae472ed79/raw/3b61026da30d04c3a827d3436ae3983674de166c/gistfile1.py
# python3 mintest.py  # I can't see what's happening (because Xvfb not real X Server), but it doesn't error!

```

I'm not longer getting segfaults, or errors! and it sounds like @sfrazt isn't either?

Finally, we have a chat room now, https://gitter.im/harvimt/quamash?utm_source=share-link&utm_medium=link&utm_campaign=share-link which may easier for some of this stuff.

**Comment by horazont** [comment]
Note, InvalidStateErrors related to connections is exactly what #25 is about.
