### ISSUE TITLE
Debug output appears to indicate default executor even when default isn't used

### ISSUE THREAD

**Issue by dg1727** [harvimt/quamash#31]
The user's program can run the following line to enable debug output on stderr/stdout:  

`logging.basicConfig(level=logging.DEBUG)`

The debug output states the following message, apparently unconditionally, when user code runs `.run_in_executor()`:  

`DEBUG:quamash.QEventLoop:Using default executor`

... and the source code seems to confirm this [\__init\__.py starting at line 480, run_in_executor() method].  

Hopefully the logic can be updated to print the mentioned message only when the default executor is being used.

**Comment by harvimt** [comment]
That's a weird error.

I don't think we expected anyone to use the debugging info unless they were actually working on the project.

**Comment by harvimt** [comment]
This fix will be released in version 0.6 when it is released.
