### ISSUE TITLE
How can I set the `loop` variable to global ?

### ISSUE THREAD

**Issue by cosven** [harvimt/quamash#39]
Hello

I have a problem in using.

In my case:
I have two files. **main.py** and  **mainwindow.py**
```
# main.py

if __name__ == "__main__":
   app = QApplication(sys.argv)
   loop = QEventLoop(app)
   asyncio.set_event_loop(loop)
   w = MainWindow()
   w.show()
   loop.run_forever()
```

```
# mainwindow.py
class MainWindow():
    ...
    # I want to access the variable "loop" here
    # I have tried "global" and "nonlocal" keywords, but it did no use
```

my question is that how can i use the variable in **mainwindow.py** ?
Can you help me ? thanks ~

**Comment by harvimt** [comment]
the standard way is to use `asyncio.get_event_loop()`, but you could also set a variable on application or whatever.

**Comment by harvimt** [comment]
Python doesn't have real "global" variables, the most it has is module global variables, so if you want to access `main.loop` from the `mainwindow` module, do `from .main import loop` in mainwindow.py.

The `global` and `nonlocal` keywords are for writing to globals and nonlocals in python not reading from them (though they can help with readability when accessing a variable from a nested scope).

Also this is a python question not really relevant to quamash more appropriate to stackoverflow or (not that I mind).

You may wish to review the [python scoping rules](https://stackoverflow.com/questions/291978/short-description-of-python-scoping-rules) and [packages and modules](http://www.tutorialspoint.com/python/python_modules.htm)

**Comment by cosven** [comment]
Thanks a lot. 

I think the `asyncio.get_event_loop()` function  may help me solving the problem.

**Comment by cosven** [comment]
Annotatiion:

`asyncio.get_event_loop()` can give us the event_loop object, however, it only works in main-thread since _the event loop must be run in the main thread_. 

As a result, if you want to get event_loop object in other thread, maybe you need to set a variable on application.

> To schedule a callback from a different thread, the `AbstractEventLoop.call_soon_threadsafe()` method should be used. 
> Example: `loop.call_soon_threadsafe(callback, *args)`
You can not use `asyncio.get_event_loop` to get loop object here.

**Comment by harvimt** [comment]
Correct, there's a feature card somewhere to make a QEventLoop policy for better threading support.

I don't have much motivation to work on quamash these days though, so it's pretty unlikely to get done.
