### ISSUE TITLE
Pep8 remark and pythonification of the code

### ISSUE THREAD

**Issue by Insoleet** [harvimt/quamash#48]
I'm having this pep8 erros in quamash files : 
  * "PEP8 : indentation contains tabs" -> These should be 4 spaces indents

Also, it's not a good practice in general to implement classes in the \__init\__.py file.

http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html

**Comment by aknuds1** [comment]
Mark has deliberately chosen to use tabs rather than spaces in this project.

**Comment by Insoleet** [comment]
Weird choice. Really annoying to force to ignore pep8 warning when we want to contribute to quamash... :/

**Comment by aknuds1** [comment]
@Insoleet If you use [Editorconfig](http://editorconfig.org/) the rules should be applied automatically.

**Comment by Insoleet** [comment]
Interesting. Installing it right now in my PyCharm instance :) 

I think the remarks for the __init__.py still stands, thought.

**Comment by aknuds1** [comment]
But why?

**Comment by Insoleet** [comment]
For multiple reasons.
  - logging with outputs information from `__init__` module, not really verbose
  - the code separation between the different modules (windows, unix, common) is not clear. QEventLoop could be in the common file, imported in the `__init__.py` for example. 

Finally, importing quamash can have a lot of side effects because of the import of the __init__.py. When we import quamash, it triggers all the code in __init__.py, which then imports other modules needed by the code. These side effects could be unwanted when we only import a simple package. Generally when we import a simple package, we do not want it to have a lot of effects.

**Comment by harvimt** [comment]
Yeah I've been wanting to move stuff around for awhile, but I've been sort
of unclear exactly how it should be done, and Arve seems to really like it
this way though, and I think my weak desire for some "more logical" and
"balanced" (most of the code is in one file) without specifics combined
with the Aumanian evidence of Arve's position to keep it the way he wrote
it sort of decided the issue.

I think it would make sense to divide the executor and the eventloop into
their own modules, then have a _common for stuff shared between those.
probably merge util.py into _common.py

In other projects I've put the __author__ and __version__ and stuff into an
__about__.py to avoid the `import quamash` in setup.py

**Comment by aknuds1** [comment]
It's not as if I feel strongly about this, just that there's little point in moving things around unless you gain something from it.

**Comment by Insoleet** [comment]
Well as quamash can be a new standard for PyQt with Python 3.5 (thanks to async and await new keywords), I think it's important to make the package code more standard and clean.

**Comment by aknuds1** [comment]
My argument is it's better to fix bugs and then worry about clean code, though.

**Comment by Insoleet** [comment]
Oh, I agree. But for example, this bug/feature ( https://github.com/harvimt/quamash/issues/45 ) will need some change in the code organization.
Also, bugs can happen due to have too much core code in the `__init__.py` package file. This happens (happened?) to the Django project for example.
Generally,  one wants the `__init__.py` file to present the available API of the package.

**Comment by aknuds1** [comment]
I'm inclined to think this issue is to vague, really. When it comes to indentation, we should simply decide whether to keep the current standard (tabs) or make the switch to spaces. This is up to Mark really.

When it comes to restructuring, it'd be better to raise separate issues IMO. If there are actual bugs, well, create issues for said bugs.

**Comment by Insoleet** [comment]
Oh the issue is just here to start a discussion on this topic.

**Comment by aknuds1** [comment]
Sounds like we might as well close it then?

**Comment by Insoleet** [comment]
Yes, sure. You can close the issue if you do not think that it's a valid one ! It's up to you :)

**Comment by harvimt** [comment]
yeah I'm gonna close this for now, but a more modular quamash might be good... I've got ideas swirling in my head for how I want to arrange this.
