### ISSUE TITLE
Do not meddle with the PyQt namespace

### ISSUE THREAD

**Issue by sbourdeauducq** [harvimt/quamash#57]
i.e. remove this:
https://github.com/harvimt/quamash/blob/master/quamash/__init__.py#L52

**Comment by sbourdeauducq** [comment]
Well, the hack is still there. Is it absolutely necessary?

**Comment by harvimt** [comment]
No. It's been fixed in another branch for a while.

Also it's like the least ugly hack in quamash.

**Comment by sbourdeauducq** [comment]
Can you please point to the branch you are referring to?

**Comment by harvimt** [comment]
depinject5realz I think. It's in a PR, and it needs to be rebased off
master.
