### ISSUE TITLE
aiohttp do not work with QEventLoop

### ISSUE THREAD

**Issue by inzem77** [harvimt/quamash#61]
Hello!
I am writing Qt web socket chat. I have next code of function:
```
async def master():
    with aiohttp.ClientSession() as session:# make session
        async with session.post('http://127.0.0.1:8080', data={'nickname': 'Admin'}) as response:
            assert response.status == 200
            print(await response.text())

        async with session.ws_connect('http://127.0.0.1:8080/127.0.0.1/ws/') as ws:
            async for msg in ws:
                if msg.tp == aiohttp.MsgType.text:
                    print(msg.data)
```
This function works with loop = asyncio.get_event_loop()
but does not works QEventLoop

I am using version aiohttp==0.20.2, asyncio==3.4.3, Quamash==0.5.4, Python3.5

**Comment by harvimt** [comment]
Is this on windows?

**Comment by inzem77** [comment]
No, it is on linux 
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by harvimt** [comment]
Full error message?

**Comment by inzem77** [comment]
i do not have error. If i use asyncio.get_event_loop() script send post request, if i use QEventLoop script do not send post request.
Full script read on http://pastebin.com/aR2JUN2u

**Comment by harvimt** [comment]
you should be doing `asyncio.set_event_loop(loop)` (where loop is instance of QEventLoop)

**Comment by inzem77** [comment]
Ui form file http://pastebin.com/SQGKA7E6

**Comment by inzem77** [comment]
it is working! Thank you!
