### ISSUE TITLE
WinError 995 confuses Quamash

### ISSUE THREAD

**Issue by KirillMysnik** [harvimt/quamash#77]
## WinError 995
It's an alias for [ERROR_OPERATION_ABORTED](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681388(v=vs.85).aspx#ERROR_OPERATION_ABORTED):

> The I/O operation has been aborted because of either a thread exit or an application request.

## The issue
Cancelling the I/O-based coroutine (e.g. `asyncio.open_connection`) might lead to an `OSError` (with that WinError 995 as a reason) somewhere inside of `asyncio` machinery.

### Minimal code to reproduce:
```python
import asyncio
import sys

from PyQt5.QtWidgets import QApplication

from quamash import QEventLoop


async def main(*, loop):
    f = asyncio.ensure_future(
        asyncio.open_connection('example.org', 8888, loop=loop),
        loop=loop
    )

    await asyncio.sleep(0.1, loop=loop)
    f.cancel()


app = QApplication(sys.argv)

with QEventLoop(app) as loop:
    asyncio.set_event_loop(loop)
    loop.run_until_complete(main(loop=loop))
```
### Output:
```
(venv) D:\Python\requested-cctv>python quamash-test.py
Event callback failed: [WinError 995] Операция ввода/вывода была прервана из-за завершения потока команд или по запросу приложения
Traceback (most recent call last):
  File "D:\Python\requested-cctv\venv\lib\site-packages\quamash\_windows.py", line 41, in _process_events
    value = callback(transferred, key, ov)
  File "c:\python36\Lib\asyncio\windows_events.py", line 514, in finish_connect
    ov.getresult()
OSError: [WinError 995] ╬яхЁрЎш  ттюфр/т√тюфр с√ыр яЁхЁтрэр шч-чр чртхЁ°хэш  яюЄюър ъюьрэф шыш яю чряЁюёє яЁшыюцхэш 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\requested-cctv\venv\lib\site-packages\quamash\_windows.py", line 44, in _process_events
    f.set_exception(e)
  File "c:\python36\Lib\asyncio\windows_events.py", line 79, in set_exception
    super().set_exception(exception)
asyncio.base_futures.InvalidStateError: invalid state

(venv) D:\Python\requested-cctv>
```
The application crashes.

Now that's an exception in Quamash when it tries to set that `OSError` as an exception on the local `f` variable in `_windows._ProactorEventLoop._process_events`.
Printing that `f` variable gives
> `<_OverlappedFuture cancelled>`

If done without Qt and Quamash, this `OSError` doesn't appear anywhere.

**Note:** The bug is inconsistent. Sometimes (rarely) it doesn't occur.

### System info
Windows 10 x64, Python 3.6.0

**Comment by harvimt** [comment]
That would explain a lot. (About failing tests on Windows)

I'm heading out for a brief vacation, but I'll be back on Tuesday.

I'll take a closer look then.
