### ISSUE TITLE
will this work with Tornado and other asyncio loops?

### ISSUE THREAD

**Issue by rudolfolah** [harvimt/quamash#92]
I'm wondering if it's possible to get this to work with Tornado web framework which can use asyncio. Has anyone tried this?

**Comment by harvimt** [comment]
I don't think so.

You could run the Tornado event loop in one thread and the Quamash event loop in another; however, I don't think that will work very well.

Probably better off having a callback on the tornado event loop that just calls `QApplication.processEvents()`
