### ISSUE TITLE
Event loop stopped before Future completed

### ISSUE THREAD

**Issue by metazoic** [harvimt/quamash#96]
Running the following code
```python
import sys
import asyncio
from quamash import QEventLoop
import PyQt5.QtWidgets as QW

async def coroutine():
	message_box = QW.QMessageBox(QW.QMessageBox.Warning, 'test', 'hey')
	message_box.show()
	await asyncio.sleep(5)

app = QW.QApplication(sys.argv)
with QEventLoop(app) as event_loop:
	asyncio.set_event_loop(event_loop)
	event_loop.run_until_complete(coroutine())
```
shows a message box for 5 seconds. Any idea why hitting the OK button on the box before it disappears results in the following error?
```python
Traceback (most recent call last):
  File "c:\Users\Desktop\quamash1.py", line 14, in <module>
    event_loop.run_until_complete(coroutine())
  File "C:\Users\Anaconda3\lib\site-packages\quamash\__init__.py", line 285, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```
#### Versions:
python: 3.6.6
quamash: 0.6.0
pyqt: 5.9.2
qt: 5.9.6

**Comment by harvimt** [comment]
This is a very contrived example. I'm not sure what you're trying to do, but this sort of application structure is terrible.

Relying on the Future exiting, to kill the event loop and close all the windows: don't do that.

**Comment by harvimt** [comment]
What I think is happening is the app will exit after all windows attached to the app are closed (at least by default), so you close the window, and then it quits the loop before the Future completes.

**Comment by metazoic** [comment]
This is a contrived example because I've tried to provide the simplest code that replicates the issue I'm experiencing in a more complex application. (Caveat: I'm very new to asyncio.)

Not sure if this answers your second comment, but even adding ```app.exec()``` at the end of the ```with``` block results in the same error.

**Comment by harvimt** [comment]
Naturally. The quamash event loop already stopped, you'd need a
loop.run_forever.

What I'm trying to say is don't use loop.run_until_complete with
interactive code. Use run_forever.

**Comment by metazoic** [comment]
Events are processed once [here](https://github.com/harvimt/quamash/blob/master/quamash/__init__.py#L283). What do you think about replacing that line with
```python
while not future.done():
    self.__app.processEvents()
```
to continue processing events until the Future is done. This fix avoids the RuntimeError. (A similar fix is mentioned at https://github.com/erdewit/tws_async).

**Comment by harvimt** [comment]
Doesn't that just make the semantics of run_until_complete wrong?

**Comment by cheng-lin-aeolus** [comment]
> Doesn't that just make the semantics of run_until_complete wrong?

I got the same issue and @metazoic 's code works for me without problem.
Why do you think the semantics is wrong?

**Comment by harvimt** [comment]
The code working is immaterial to whether the semantics are correct.

run_until_complete has particular semantics defined by the PEP, and I can't
just... not follow the standard when the point of an adapter is to follow
the API.

If you want the loop to run forever... then use `loop.run_forever()` (and
use other interactions to pause the loop).

**Comment by harvimt** [comment]
the other option of course is to extend the API somehow for Qt specific
stuff... I'm not exactly sure how that would look.
